name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build-macos:
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        target: [dmg, zip]
        # include:
        #   - arch: arm64
        #     target: dmg

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install Python 3.11.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.4'

    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Package application for macOS ${{ matrix.arch }} ${{ matrix.target }}
      run: npx electron-forge make --platform=darwin --arch=${{ matrix.arch }} --targets="@electron-forge/maker-${{ matrix.target }}" --icon=public/avatar

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-app-${{ matrix.arch }}-${{ matrix.target }}
        path: out/make/**/*.${{ matrix.target == 'dmg' && 'dmg' || 'zip' }}

  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
        target: [deb, zip]
        # include:
        #   - arch: x64
        #     target: deb

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Package application for Linux ${{ matrix.arch }} ${{ matrix.target }}
      run: npx electron-forge make --platform=linux --arch=${{ matrix.arch }} --targets="@electron-forge/maker-${{ matrix.target }}" --icon=public/avatar

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-app-${{ matrix.arch }}-${{ matrix.target }}
        path: out/make/**/*.${{ matrix.target == 'deb' && 'deb' || 'zip' }}
    
  build-windows:
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, ia32]
        target: [squirrel, zip]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
    
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

    - name: Package application for Windows ${{ matrix.arch }} ${{ matrix.target }}
      run: npx electron-forge make --platform=win32 --arch=${{ matrix.arch }} --targets="@electron-forge/maker-${{ matrix.target }}" --icon=public/avatar

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: electron-app-${{ matrix.arch }}-${{ matrix.target }}
        path: out/make/**/*.${{ matrix.target == 'squirrel' && 'exe' || 'zip' }}
